### ISSUE TITLE
Create Dockerfile

### ISSUE THREAD

**Issue by bersace** [dalibo/ldap2pg#202]
On docker only platform, having an official ldap2pg Docker image is great.

## Tasks

- [x] Create Dockerfile
- [x] Ensure README on Docker Hub.
- [x] Register automated build in Docker hub.
- [x] Add badge on README
- [x] Document Docker usage

I offer mentorship on this issue :-)

**Comment by Stanislasss** [comment]
Hi @bersace ,
Does a Dockerfile like below would be ok for you? Or are you waiting for something else:

```
FROM python:3.7

RUN  apt-get update && apt-get install -y libldap2-dev libsasl2-dev python3-pip && pip install --upgrade pip && pip install psycopg2==2.7.3.2 ldap2pg # installing 
#Installing psycopg2==2.7.3.2 avoiding warning on tool run:
#The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.```

**Comment by bersace** [comment]
That's a good starting point. Can you open a PR ?

**Comment by bersace** [comment]
pip is already installed in python:3.7 image.

**Comment by Stanislasss** [comment]
I'm actually upgrading pip if a new version is released in between. Is this a bad practice?

**Comment by Stanislasss** [comment]
Sure thing

**Comment by bersace** [comment]
Vielen danke @Stanislasss !!
